### ISSUE TITLE
Random crash with ACsGUI

### ISSUE THREAD

**Issue by gabidut** [AymericBdy/ACsGuis#4]
It happens at random times

WARNING: coremods are present:
  ObfuscatePlugin (unknown)
Contact their authors BEFORE contacting forge

// Hey, that tickles! Hehehe!

Time: 2/25/24 2:41 PM
Description: There was a severe problem during mod loading that has caused the game to fail

Exception in task css_load
Caused by: java.lang.RuntimeException: Fatal error while loading css sheets
	at fr.aym.acsguis.api.ACsGuiApi.lambda$reloadCssStyles$0(ACsGuiApi.java:139)
	at fr.aym.acslib.services.impl.thrload.DThreadedLoadingTask.run(DThreadedLoadingTask.java:39)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:266)
	at java.util.concurrent.FutureTask.run(FutureTask.java)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)
Caused by: java.lang.RuntimeException: Fatal error while loading css sheets
	at fr.aym.acsguis.utils.CssReloadOrigin.loadStyles(CssReloadOrigin.java:55)
	at fr.aym.acsguis.api.ACsGuiApi.lambda$reloadCssStyles$0(ACsGuiApi.java:137)
	... 7 more
Caused by: java.lang.NullPointerException
	at fr.aym.acslib.impl.services.error_tracking.ACsLibErrorManager$LocatedErrorListImpl.clear(ACsLibErrorManager.java:182)
	at fr.aym.acslib.impl.services.error_tracking.ACsLibErrorManager.lambda$clear$0(ACsLibErrorManager.java:50)
	at java.util.HashMap$Values.forEach(HashMap.java:982)
	at fr.aym.acslib.impl.services.error_tracking.ACsLibErrorManager.clear(ACsLibErrorManager.java:50)
	at fr.aym.acsguis.utils.CssReloadOrigin.handlePreLoad(CssReloadOrigin.java:45)
	at fr.aym.acsguis.utils.CssReloadOrigin.loadStyles(CssReloadOrigin.java:51)
	... 8 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 11 (amd64) version 10.0
	Java Version: 1.8.0_382, Azul Systems, Inc.
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Azul Systems, Inc.
	Memory: 885414120 bytes (844 MB) / 3908042752 bytes (3727 MB) up to 7600078848 bytes (7248 MB)
	JVM Flags: 0 total; 
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2860 Optifine OptiFine_1.12.2_HD_U_G5 13 mods loaded, 13 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID            | Version      | Source                                                     | Signature |
	|:----- |:------------- |:------------ |:---------------------------------------------------------- |:--------- |
	| LCHIJ | minecraft     | 1.12.2       | minecraft.jar                                              | None      |
	| LCHIJ | mcp           | 9.42         | minecraft.jar                                              | None      |
	| LCHIJ | FML           | 8.0.99.99    | forge-1.12.2-14.23.5.2860_mapped_stable_39-1.12-recomp.jar | None      |
	| LCHIJ | forge         | 14.23.5.2860 | forge-1.12.2-14.23.5.2860_mapped_stable_39-1.12-recomp.jar | None      |
	| LCHIJ | obfuscate     | 0.4.2        | minecraft.jar                                              | None      |
	| LCHIJ | dynamx_basics | 1.0.8        | WesterLife-MOD.main                                        | None      |
	| LCHIJ | westerlife    | 1.5.8-2      | WesterLife-MOD.main                                        | None      |
	| LCHIJ | sdm           | 1.0          | simpledatabasemanager-1.0.jar                              | None      |
	| LCHIE | acslib        | 1.2.12       | ACsGuis-1.2.12.jar                                         | None      |
	| LCHI  | better_lights | 0.0.3        | BetterLights-0.0.3.PREVIEW-all.jar                         | None      |
	| LCHI  | modularvc     | 1.1.1        | ModularVoiceChat-1.1.1.jar                                 | None      |
	| LCHI  | mcgltf-dynamx | 1.0          | DynamX-4.1.0-dev16-all.jar                                 | None      |
	| LCHI  | dynamxmod     | 4.1.0        | DynamX-4.1.0-dev16-all.jar                                 | None      |

	Loaded coremods (and transformers): 
ObfuscatePlugin (unknown)
  com.mrcrayfish.obfuscate.asm.ObfuscateTransformer
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 551.23' Renderer: 'NVIDIA GeForce RTX 3070/PCIe/SSE2'
	OptiFine Version: OptiFine_1.12.2_HD_U_G5
	OptiFine Build: 20210124-142939
	Render Distance Chunks: 18
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.6.0 NVIDIA 551.23
	OpenGlRenderer: NVIDIA GeForce RTX 3070/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 16
[14:41:07] [Client thread/INFO] [STDOUT]: [net.minecraft.init.Bootstrap:printToSYSOUT:553]: #@!@# Game crashed! Crash report saved to: #@!@# C:\Users\gabid\Desktop\WesterLife-MOD\WesterLife\.\crash-reports\crash-2024-02-25_14.41.06-client.txt
AL lib: (EE) alc_cleanup: 1 device not closed
Disconnected from the target VM, address: '127.0.0.1:4866', transport: 'socket'

Process finished with exit code -1

**Comment by Safraann** [comment]
Any news on this ? Still happening with what seems to be latest version `ACsGuis-1.4.2-beta-all`
